import type { PagComposition } from '../src/export/pag/types'

export const solidFixture: PagComposition = {
  id: 1,
  width: 320,
  height: 180,
  duration: 30,
  frameRate: 30,
  backgroundColor: { red: 255, green: 255, blue: 255 },
  images: [
    {
      id: 1,
      width: 1,
      height: 1,
      explicitSize: true,
      bytes: Uint8Array.from([
        0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
        0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
        0x08, 0x04, 0x00, 0x00, 0x00, 0xb5, 0x1c, 0x0c, 0x02, 0x00, 0x00, 0x00,
        0x0b, 0x49, 0x44, 0x41, 0x54, 0x78, 0xda, 0x63, 0x64, 0xf8, 0x0f, 0x00,
        0x01, 0x05, 0x01, 0x01, 0x27, 0x18, 0xe3, 0x66, 0x00, 0x00, 0x00, 0x00,
        0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
      ]),
    },
  ],
  compositions: [
    {
      id: 2,
      width: 100,
      height: 100,
      duration: 30,
      frameRate: 30,
      backgroundColor: { red: 255, green: 255, blue: 255 },
      layers: [
        {
          type: 'shape',
          id: 8,
          name: 'Overlay',
          startTime: 0,
          duration: 30,
          transform: {},
          geometry: {
            type: 'rectangle',
            size: { x: 100, y: 100 },
            position: { x: 50, y: 50 },
            roundness: 8,
          },
          fillRule: 0,
          fill: {
            kind: 'gradient',
            fillType: 0,
            startPoint: { x: 0, y: 50 },
            endPoint: { x: 100, y: 50 },
            colors: {
              alphaStops: [
                { position: 0, midpoint: 0.5, opacity: 255 },
                { position: 1, midpoint: 0.5, opacity: 255 },
              ],
              colorStops: [
                { position: 0, midpoint: 0.5, color: { red: 35, green: 164, blue: 244 } },
                { position: 1, midpoint: 0.5, color: { red: 254, green: 245, blue: 244 } },
              ],
            },
            opacity: 255,
          },
        },
      ],
    },
  ],
  layers: [
    {
      type: 'precompose',
      id: 7,
      name: 'Multi Fill',
      startTime: 0,
      duration: 30,
      compositionId: 2,
      compositionStartTime: 0,
      transform: {},
    },
    {
      type: 'text',
      id: 6,
      name: 'Title',
      startTime: 0,
      duration: 30,
      transform: { position: { x: 20, y: 32 } },
      sourceText: {
        applyFill: true,
        applyStroke: false,
        boxText: false,
        fauxBold: false,
        fauxItalic: false,
        strokeOverFill: true,
        baselineShift: 0,
        firstBaseLine: 0,
        boxTextPos: { x: 0, y: 0 },
        boxTextSize: { x: 0, y: 0 },
        fillColor: { red: 10, green: 20, blue: 30 },
        fontSize: 24,
        strokeColor: { red: 0, green: 0, blue: 0 },
        strokeWidth: 1,
        text: 'PAG Text',
        justification: 0,
        leading: 0,
        tracking: 0,
        fontFamily: 'Inter',
        fontStyle: 'Regular',
      },
    },
    {
      type: 'solid',
      id: 2,
      name: 'Background',
      startTime: 0,
      duration: 30,
      width: 320,
      height: 180,
      color: { red: 255, green: 128, blue: 0 },
      blendMode: 1,
      transform: { position: { x: 12, y: 8 }, opacity: 204 },
    },
    {
      type: 'shape',
      id: 5,
      active: false,
      name: 'Badge Matte',
      startTime: 0,
      duration: 30,
      transform: {},
      geometry: {
        type: 'rectangle',
        size: {
          keyframes: [{
            startTime: 0,
            endTime: 15,
            startValue: { x: 4, y: 90 },
            endValue: { x: 160, y: 90 },
            interpolation: 1,
          }],
        },
        position: {
          keyframes: [{
            startTime: 0,
            endTime: 15,
            startValue: { x: 2, y: 45 },
            endValue: { x: 80, y: 45 },
            interpolation: 1,
          }],
        },
        roundness: 0,
      },
      fill: { color: { red: 255, green: 255, blue: 255 }, opacity: 255 },
      fillRule: 0,
    },
    {
      type: 'shape',
      id: 3,
      name: 'Badge',
      trackMatteType: 'alpha',
      startTime: 0,
      duration: 30,
      transform: {
        position: {
          keyframes: [
            {
              startTime: 0,
              endTime: 15,
              startValue: { x: 100, y: 40 },
              endValue: { x: 160, y: 40 },
              interpolation: 1,
            },
            {
              startTime: 15,
              endTime: 30,
              startValue: { x: 160, y: 40 },
              endValue: { x: 200, y: 80 },
              interpolation: 2,
              bezier: [{ out: { x: 0.42, y: 0 }, in: { x: 0.58, y: 1 } }],
            },
          ],
        },
      },
      effects: [
        {
          type: 'fast-blur',
          blurriness: {
            keyframes: [
              {
                startTime: 0,
                endTime: 18,
                startValue: 21.2,
                endValue: 60,
                interpolation: 2,
                bezier: [{ out: { x: 0.5, y: 0 }, in: { x: 0.5, y: 1 } }],
              },
            ],
          },
          blurDimensions: 0,
          repeatEdgePixels: true,
          effectOpacity: 255,
        },
      ],
      geometry: {
        type: 'rectangle',
        size: { x: 80, y: 40 },
        position: { x: 40, y: 20 },
        roundness: 8,
      },
      fill: { color: { red: 20, green: 110, blue: 240 }, opacity: 255 },
      fillRule: 0,
      stroke: {
        color: { red: 255, green: 255, blue: 255 },
        opacity: 255,
        width: 2,
        lineCap: 1,
        lineJoin: 1,
        miterLimit: 4,
      },
    },
    {
      type: 'image',
      id: 4,
      imageId: 1,
      name: 'Picture',
      startTime: 0,
      duration: 30,
      transform: { position: { x: 220, y: 80 }, scale: { x: 40, y: 40 } },
      masks: [
        {
          id: 1,
          mode: 'intersect',
          inverted: true,
          feather: { x: 2, y: 3 },
          opacity: 200,
          expansion: 1.5,
          commands: [
            { type: 'move', values: [0, 0] },
            { type: 'line', values: [1, 0] },
            { type: 'line', values: [1, 1] },
            { type: 'line', values: [0, 1] },
            { type: 'close', values: [] },
          ],
        },
      ],
    },
  ],
}
